
#' Generate initial status for nodes
#'
#' This function generates the initial status for nodes, in terms of the presence of management information or focal species 
#'
#' Updated 2020-06-02

#' @param ip the proportion of initial locations for presence
#' @param loctype the type of locations where initial presence occurs: 'random' indicates all equally likely, 'upedge' indicates that nodes closest to the upper edge have presence, 'rightedge' indicates that nodes closest to the right edge have presence
#' @param numinit the number of initial locations for presence
#' @param numorprop 'num' indicates initial number for presence, 'prop' indicates initial proportion
#' @param plotmp if T, then map of presence and absence is plotted
#' @param xymat n by 2 matrix of geographic coordinates, provided for a particular system or generated by function genlocs

#' @keywords initial conditions
#' @export
#' @examples
#' x2 <- initvals(j2 <- genlocs(extx=c(0,50), exty=c(0,50), nn=100, rand=TRUE),loctype='random', ip=0.1, numorprop='prop', plotmp=T)
#' x3 <- initvals(j2 <- genlocs(extx=c(0,50), exty=c(0,50), nn=100, rand=TRUE),loctype='upedge', ip=0.3, numorprop='prop', plotmp=T)
#' x4 <- initvals(j2 <- genlocs(extx=c(0,50), exty=c(0,50), nn=100, rand=TRUE), loctype='rightedge', ip=0.3, numorprop='prop',plotmp=T)
#' x5 <- initvals(matrix(c(1,5, 2,5, 3,5, 4,5), byrow=T, ncol=2), loctype='upedge', numorprop='num', numinit=2, plotmp=T) 
#' x6 <- initvals(matrix(c(5,1, 5,2, 5,3, 5,4), byrow=T, ncol=2), loctype='rightedge', numorprop='num', numinit=2, plotmp=T) 


initvals <- function(xymat, loctype, ip, numinit, numorprop, plotmp=F){

  nodlen <- dim(xymat)[1]


  if(numorprop == 'prop'){numinit <- round(nodlen*ip)}

  initvec <- 0*(1:nodlen)

  if(loctype == 'random'){
    j <- sample(x=1:nodlen, size=numinit)
    initvec[j] <- 1
  }

  else if (loctype == 'upedge'){
    temp1 <- rank(xymat[,2]) > nodlen - numinit
    temp2 <- cumsum(temp1) <= numinit
    initvec[temp1 & temp2] <- 1
  }

  else if (loctype == 'rightedge'){
    temp1 <- rank(xymat[,1]) > nodlen - numinit
    temp2 <- cumsum(temp1) <= numinit
    initvec[temp1 & temp2] <- 1
  }

  if(plotmp){
    plot(xymat)
    points(xymat[initvec==1,], pch=16)
  }


  initvec
}