
#' Changes management info status and bioentity establishment status at each node across multiple time steps
#'
#' This function gives the info status and establishment status at each node after multiple time steps. Its use follows use of the function \code{setup2}, or another source of node locations and initial conditions.  (Note that communication and dispersal status are given for the beginning of the time step (rather than for the end), so the corresponding output for these has length equal to the number of time steps plus 1.  In contrast, adoption and establishment output is of length equal to the number of time steps.) It uses the following functions, as needed: genmovnet, spreadstep, makedec, and estab. It draws on output from function setup2 in terms of whether communication occurs (estinfo), generated geographic locations of nodes as needed (genloc), and the initial locations for management information and the bioentity.

#'
#' Updated 2020-07-13

#' @param nsteps number of time steps to be evaluated

#' @param infon is T if estimated effect size exceeds threshold for communication (so communication can occur), F otherwise (can be evaluated in estinfo and/or setup2)

#' @param readcomamn if T, the communication adjacency matrix is read in rather than being generated by function genmovnet
#' @param readdispamn if T, the dispersal adjacency matrix is read in rather than being generated by function genmovnet
#' @param comamn communication adjacency matrix, read in if readcomamn=T
#' @param dispamn dispersal adjacency matrix, read in if readdispamn=T
#' @param xymatinn matrix of x,y coordinates of nodes

#' @param distfcn com (genmovnet) the function of distance used to estimate movement probability - 'random' (not related to distance) or 'powerlaw' 
#' @param lktypecn com (genmovnet) link type, pa is presence/absence (unweighted, occurence/non-occurence), pr is a probability of occurence, wtd1 is general weight
#' @param placn com (genmovnet) inverse power law parameter a in ad^(-b)
#' @param plbcn com (genmovnet) inverse power law parameter b in ad^(-b)
#' @param randpcn com (genmovnet) random case, probably of link
#' @param tlinkcn com (genmovnet) threshold for whether link exists (probability in some cases)

#' @param distfdn disp (genmovnet) the function of distance used to estimate movement probability - 'random' (not related to distance) or 'powerlaw' 
#' @param lktypedn disp (genmovnet) link type, pa is presence/absence (unweighted, occurence/non-occurence), pr is a probability of occurence, wtd1 is general weight
#' @param pladn disp (genmovnet) inverse power law parameter a in ad^(-b)
#' @param plbdn disp (genmovnet) inverse power law parameter b in ad^(-b)
#' @param randpdn disp (genmovnet) random case, probably of link
#' @param tlinkdn disp (genmovnet) threshold for whether link exists (probability in some cases)

#' @param diag1cn com (spreadstep) if T, diagonal of adj mat is given value 1
#' @param mattypecn com (spreadstep) 'fromto' indicates that rows are sources and columns are sinks, 'tofrom' indicates that columns are sources and rows are sinks
#' @param max1cn com (spreadstep) if T, values in vect2 greater than 1 are replaced by 1
#' @param vect1cn com (spreadstep) status of nodes before spread

#' @param diag1dn disp (spreadstep) if T, diagonal of adj mat is given value 1
#' @param mattypedn disp (spreadstep) 'fromto' indicates that rows are sources and columns are sinks, 'tofrom' indicates that columns are sources and rows are sinks
#' @param max1dn disp (spreadstep) if T, values in vect2 greater than 1 are replaced by 1
#' @param vect1dn disp (spreadstep) status of nodes before spread

#' @param adpmn (makedec) mean probability of adopting management if informed
#' @param adpsdn (makedec) sd in truncated normal distribution of probability of adoption
#' @param comvec vector of 1=info is present, 0=info is not present
#' @param padoptn vector of probabilities of adoption if informed for nodes in the network (\code{readpadopt} determines whether \code{padopt} is read in to \code{makedec} or generated within \code{makedec} based on \code{adpm} and \code{adpsd})
#' @param readpadoptn if T, then a VECTOR of padopt values is read in; if F, \code{adpm} and \code{adpsd} are used to generate the vector

#' @param estpmn (estab) mean probability of establishment (new or CONTINUED) in absence of management
#' @param estpsdn (estab) sd in probability of establishment in truncated normal distribution
#' @param efmnn (estab) mean management effect (proportional reduction in estabp) 
#' @param efsdn (estab) sd of management effect
#' @param pestabn (estab) vector of probabilities of establishment (read in or generated when the function is run, depending on \code{readpestab} equal to T or F)
#' @param readpestabn (estab) if T, then a vector \code{pestabn} is read in; otherwise the vector is generated using \code{estpmn} and \code{estpsd}

#' @param plotmpn if T, plots of resulting presence of information and species are generated

#' @keywords simulation experiments
#' @export 
#' @import truncnorm

#' @examples
#' x2 <- ntsteps2(nsteps=3, infon=T, xymatinn=matrix(c(1,1, 1,2, 1,3, 2,1, 2,2, 2,3),byrow=T,ncol=2), vect1cn=c(1,1,1,0,0,0), vect1dn=c(0,0,0,1,1,1), distfcn='powerlaw', lktypecn='pa', placn=1, plbcn=1, tlinkcn=0.1, distfdn='powerlaw', lktypedn='pa', pladn=1, plbdn=1, tlinkdn=0.1, readcomamn=F, readdispamn=F, diag1cn=T, mattypecn='fromto', max1cn=T, diag1dn=T, mattypedn='fromto', adpmn=0.5, adpsdn=0.1, estpmn=0.5, estpsdn=0.1, manredestab2=T, efmnn=0.5, efsdn=0.1,  max1dn=T, readpestabn=F, readpadoptn=F, plotmpn=T)

#' x2z <- ntsteps2(nsteps=3, infon=T, xymatinn=matrix(c(1,1, 1,2, 1,3, 2,1, 2,2, 2,3),byrow=T,ncol=2), vect1cn=c(1,1,1,0,0,0), vect1dn=c(0,0,0,1,1,1), distfcn='powerlaw', lktypecn='pa', placn=0.5, plbcn=2, tlinkcn=0.1, distfdn='powerlaw', lktypedn='pa', pladn=0.5, plbdn=2, tlinkdn=0.1, readcomamn=F, readdispamn=F, diag1cn=T, mattypecn='fromto', max1cn=T, diag1dn=T, mattypedn='fromto', adpmn=0.5, adpsdn=0.1, estpmn=0.5, estpsdn=0.1, manredestab2=T, efmnn=0.5, efsdn=0.1, max1dn=T, readpestabn=F, readpadoptn=F, plotmpn=T)

#' x3 <- ntsteps2(nsteps=2, infon=T, xymatinn=matrix(runif(n=100)*100,byrow=T,ncol=2), vect1cn=c(rep(1,10),rep(0,40)), vect1dn=sample(c(rep(1,10),rep(0,40))), distfcn='powerlaw', lktypecn='pa', placn=1, plbcn=1, tlinkcn=0.1, distfdn='powerlaw', lktypedn='pa', pladn=1, plbdn=1, tlinkdn=0.1, readcomamn=F, readdispamn=F, diag1cn=T, mattypecn='fromto', max1cn=T, diag1dn=T, mattypedn='fromto', adpmn=0.5, adpsdn=0.1, estpmn=0.5, estpsdn=0.1, manredestab2=T, efmnn=0.5, efsdn=0.1,  max1dn=T, readpestabn=F, readpadoptn=F, plotmpn=T)

#' x9 <- ntsteps2(nsteps=3, infon=T, xymatinn=matrix(c(1,1, 1,2, 1,3, 2,1, 2,2, 2,3),byrow=T,ncol=2), vect1cn=c(1,1,1,0,0,0), vect1dn=c(0,0,0,1,1,1),comamn=matrix(c(0,1,0,0,0,0, 0,0,1,0,0,0, 0,0,0,1,0,0, 0,0,0,0,1,0, 0,0,0,0,0,1, 1,0,0,0,0,0),byrow=T,ncol=6), dispamn=matrix(c(0,0,0,0,0,0, 0,0,1,0,0,0, 0,0,0,1,0,0, 0,0,0,0,1,0, 0,0,0,0,0,1, 1,0,0,0,0,0),byrow=T,ncol=6), readcomamn=T, readdispamn=T, diag1cn=T, mattypecn='fromto', max1cn=T, diag1dn=T, mattypedn='fromto', max1dn=T, adpmn=0.3, adpsdn=0.1, estpmn=0.2, estpsdn=0.1, manredestab2=T, efmnn=0.5, efsdn=0.1, readpestabn=F, readpadoptn=F, plotmpn=T)

#' x12 <- ntsteps2(nsteps=3, infon=F, xymatinn=matrix(c(1,1, 1,2, 1,3, 2,1, 2,2, 2,3),byrow=T,ncol=2), vect1cn=c(1,1,1,0,0,0), vect1dn=c(0,0,0,1,1,1), distfcn='powerlaw', lktypecn='pa', placn=1, plbcn=1, tlinkcn=0.1, distfdn='powerlaw', lktypedn='pa', pladn=1, plbdn=1, tlinkdn=0.1, readcomamn=F, readdispamn=F, diag1cn=T, mattypecn='fromto', max1cn=T, diag1dn=T, mattypedn='fromto', max1dn=T, adpmn=0.3, adpsdn=0.1, estpmn=0.2, estpsdn=0.1, manredestab2=T, efmnn=0.5, efsdn=0.1, readpestabn=F, readpadoptn=F, plotmpn=T)

#' x13 <- ntsteps2(nsteps=5, infon=T, xymatinn=matrix(c(1,1, 1,2, 1,3, 2,1, 2,2, 2,3),byrow=T,ncol=2), vect1cn=c(1,1,1,0,0,0), vect1dn=c(0,0,0,1,1,1), distfcn='powerlaw', lktypecn='pa', placn=1, plbcn=1, tlinkcn=0.1, distfdn='powerlaw', lktypedn='pa', pladn=1, plbdn=1, tlinkdn=0.1, readcomamn=F, readdispamn=F, diag1cn=T, mattypecn='fromto', max1cn=T, diag1dn=T, mattypedn='fromto', max1dn=T, adpmn=0.3, adpsdn=0.1, estpmn=0.2, estpsdn=0.1, manredestab2=T, efmnn=0.5, efsdn=0.1, readpestabn=F, readpadoptn=F, plotmpn=T)



ntsteps2 <- function(nsteps, xymatinn, infon, vect1cn, vect1dn, comamn, dispamn, readcomamn, readdispamn, distfcn, lktypecn, placn, plbcn, randpcn, tlinkcn, distfdn, lktypedn, pladn, plbdn, randpdn, tlinkdn, diag1cn, mattypecn, max1cn, diag1dn, mattypedn, max1dn, readpadoptn, padoptn, adpmn, adpsdn, estpmn, estpsdn, manredestab2, efmnn, efsdn, pestabn, readpestabn, plotmpn=F){

# Numbering of steps refers to the numbering used in the INA User's Manual (1-5)

nodlen <- nrow(xymatinn) # number of nodes

# 5. If the observed management effect exceeds threshold, or if the 'science of science' threshold is not used - the following commands are implemented
# (If these criteria are not met, there is no communication)

if(infon){ 

  # 3.1. communication adjacency matrix - underlying probabilities

  # if generating the communication adj mat (not reading it in)

  if (!readcomamn){ 
    comamn <- genmovnet(xymat=xymatinn, distf=distfcn, randp=randpcn, lktype='pr', pla=placn, plb=plbcn)
  }

  # 4.1. decision making - underlying probabilities of adoption
  
  # if generating the vector of probabilities of adoption for each node (not reading it in)

  if (!readpadoptn){
    padoptn <- truncnorm::rtruncnorm(n=nodlen, a=0, b=1, mean = adpmn, sd=adpsdn)
  }

} else if (!infon){ # 5. if there is no information spread

  if (!readcomamn){comamn <- 0}

  padoptn <- 0
}

### end first infon-determined portion for socioeconomic network


# 3.2. bioentity dispersal adjacency matrix - underlying probabilities

# if generating the bioentity dispersal network (rather than reading it in)

if (!readdispamn){ 
  dispamn <- genmovnet(xymat=xymatinn, distf=distfdn, randp=randpdn, lktype='pr', pla=pladn, plb=plbdn)  
}

# 4.2. establishment - underlying probabilities of establishment
  
  # if generating the vector of probabilities of establishment for each node (not reading it in)

  if (!readpestabn){

    pestabn <- truncnorm::rtruncnorm(n=nodlen, a=0, b=1, mean = estpmn, sd=estpsdn)
  }


# prepare output lists for timesteps

vect1cL <- as.list(1:(nsteps+1))
# communication status vector at beginning of time step
vect1cL[[1]] <- vect1cn 
vect1dL <- as.list(1:(nsteps+1))
# dispersal status at beginning of time step
vect1dL[[1]] <- vect1dn

estabvec2 <- vect1dn

decvecL <- as.list(1:nsteps)
estabvecL <- as.list(1:nsteps)

# if there is no communication, 
#   the decision is always not to adopt
if(!infon){
  vect2c <- 0*(1:nodlen)
  decvec2 <- vect2c
  padoptn <- vect2c
}

### each time step

for(j in 1:nsteps) {

if(infon){ # if estimated management effect exceeds threshold, or there is no threshold used

  # communication outcome

  # which links exist this time step
  tcomam <- comamn > matrix(runif(n=nodlen*nodlen),ncol=nodlen)

  # keep symmetric
  for (i2 in 1:(nodlen-1)){
      tcomam[i2,(i2+1):nodlen] <- tcomam[(i2+1):nodlen,i2]
  }  
  diag(tcomam) <- 1

  vect2c <- spreadstep(amat=tcomam, vect1=vect1cL[[j]], diag1=diag1cn, mattype=mattypecn, max1=max1cn) # communication

  vect1cL[[j+1]] <- vect2c

  # outcome for adoption of management

  decvec2 <- makedec(comvec=vect2c, xymat=xymatinn, padopt=padoptn, readpadopt=T, plotmp=F)

  decvecL[[j]] <- decvec2

} ### end of second infon-determined actions

# dispersal outcome 

# which links exist this time step
tdispam <- dispamn > matrix(runif(n=nodlen*nodlen),ncol=nodlen)

# keep symmetric
for (i2 in 1:(nodlen-1)){
      tdispam[i2,(i2+1):nodlen] <- tdispam[(i2+1):nodlen,i2]
}  
diag(tdispam) <- 1

# note that bioentity dispersal and communication are handled differently - only locations where the bioentity has established can be a source of spread

vect2d <- spreadstep(amat=tdispam, vect1=estabvec2, diag1=diag1dn, mattype=mattypedn, max1=max1dn) # dispersal

vect1dL[[j+1]] <- vect2d

# outcome for establishment

estabvec2 <- estab(decvec=decvec2, dispvec=vect2d, pestab=pestabn, readpestab=T, manredestab1=manredestab2, efmn=efmnn, efsd=efsdn, plotmp=F)

estabvecL[[j]] <- estabvec2

# plots, if called for

if(plotmpn){
    plot(xymatinn, main=paste('Time',j,', 1 Information, shaded = yes'))
    if(!is.null(dim(xymatinn[vect2c==1,]))){
      points(xymatinn[vect2c==1,], pch=16)
    } 
    else if(is.null(dim(xymatinn[vect2c==1,]))){
      points(xymatinn[vect2c==1,][1], xymatinn[vect2c==1,][2], pch=16)
    }

   plot(xymatinn, main=paste('Time',j,', 2 Adoption, shaded = yes'))
    if(!is.null(dim(xymatinn[decvec2==1,]))){
      points(xymatinn[decvec2==1,], pch=16)
    } 
    else if(is.null(dim(xymatinn[decvec2==1,]))){
      points(xymatinn[decvec2==1,][1], xymatinn[decvec2==1,][2], pch=16)
    }

    plot(xymatinn, main=paste('Time',j,', 3 Sp dispersal, shaded = yes'))
    if(!is.null(dim(xymatinn[vect2d==1,]))){
      points(xymatinn[vect2d==1,], pch=16)
    } 
    else if(is.null(dim(xymatinn[vect2d==1,]))){
      points(xymatinn[vect2d==1,][1], xymatinn[vect2d==1,][2], pch=16)
    }

    plot(xymatinn, main=paste('Time',j,', 4 Sp establishment, shaded = yes'))
    if(!is.null(dim(xymatinn[estabvec2==1,]))){
      points(xymatinn[estabvec2==1,], pch=16)
    } 
    else if(is.null(dim(xymatinn[estabvec2==1,]))){
      points(xymatinn[estabvec2==1,][1], xymatinn[estabvec2==1,][2], pch=16)
    }
}

} #### end of time steps

list(comamn=comamn, padoptn=padoptn, dispamn=dispamn, pestabn=pestabn, vect1cL=vect1cL, vect1dL=vect1dL, decvecL=decvecL, estabvecL=estabvecL)
}
